#!/bin/bash
#PBS -l select=1:ncpus=4:mem=16GB
#PBS -l walltime=5:00:00
#PBS -j oe
#PBS -P 12003580
#PBS -q normal

module load singularity && module load java
cd $PBS_O_WORKDIR

timestamp=$(date +%Y%m%d-%H.%M)

# Run the workflow on the test data, and write the output to output/
nextflow \
    -log test.log \
    run \
    -resume \
    main.nf \
    --bam_dir "/home/users/ntu/suffiazi/scratch/tfbs-variant-calling-nf/test-data/bam_dir" \
    --run_mode "subset" \
    --dataset_id_list "test-data/manifests/dataset-manifest-test.txt" \
    --output_dir "test-data/output" \
    -c nextflow_cluster.config \
    -with-dag workflow-reports/test-runs/dag-${timestamp}.html \
    -with-report workflow-reports/test-runs/report-${timestamp}.html \
    -with-timeline workflow-reports/test-runs/timeline-${timestamp}.html \
    --fpscore_matrix "cluster-input-dir/test-matrix"
